name: Build aarch64

on:
  push:
    paths:
      - ".github/workflows/build-aarch64.yml"
      - "aarch64.Dockerfile"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: roxedus
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          file: ./Dockerfile.aarch64
          tags: |
            roxedus/playground:hass-aarch64
